services:
  api:
    image: fawkes-api
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_URLS=http://+80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__FawkesConnection=Host=postgres;username=postgres;password=postgres;database=fawkes;TrustServerCertificate=True;
    depends_on:
      - postgres

  postgres:

    image: postgres:latest
    restart: always
    container_name: postgres
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
    environment:
      POSTGRES_DB: fawkes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    ports: 
     - "5432:5432"
    
volumes:
 postgres_data: